import { Resource } from "./types";

export const allResources: Resource[] = [
  {
    id: 1,
    title: "Normalización de Bases de Datos - Formas Normales",
    type: "video",
    concept: "Bases de Datos",
    difficulty: "Intermedio",
    duration: "18 min",
    rating: 4.8,
    reason: "Tu dominio en este concepto es del 55%. Este recurso refuerza los fundamentos de normalización, donde has mostrado dificultades en los últimos 3 ejercicios.",
    content: "Contenido del video sobre normalización de bases de datos...",
    confidence: 92,
    improvement: 8,
    isRecommended: true,
    tags: ["SQL", "Relacional", "Diseño"],
  },
  {
    id: 2,
    title: "Ejercicios Prácticos de Deep Learning",
    type: "exercise",
    concept: "Deep Learning",
    difficulty: "Intermedio",
    duration: "30 min",
    rating: 4.6,
    reason: "Reforzar concepto con dominio medio (65%). La práctica te ayudará a consolidar el conocimiento.",
    content: "¿Cuál es la función de activación más común en redes neuronales profundas?\n\nSelecciona la respuesta correcta:",
    confidence: 87,
    improvement: 6,
    isRecommended: true,
    tags: ["PyTorch", "Práctica", "Backpropagation"],
  },
  {
    id: 3,
    title: "Lectura: Arquitecturas de Atención",
    type: "reading",
    concept: "Knowledge Tracing",
    difficulty: "Avanzado",
    duration: "20 min",
    rating: 4.9,
    reason: "Tienes un buen dominio (90%) en Knowledge Tracing. Este tema es el siguiente paso natural.",
    content: `Las arquitecturas de atención son mecanismos que permiten a los modelos enfocarse en partes específicas de la entrada al procesar información.\n\nEn el contexto de Knowledge Tracing, el modelo SAKT utiliza mecanismos de auto-atención para:\n\n1. Identificar qué interacciones pasadas son más relevantes\n2. Ponderar la importancia de cada concepto\n3. Generar representaciones contextuales del estado de conocimiento`,
    confidence: 91,
    improvement: 5,
    isRecommended: true,
    tags: ["Transformers", "SAKT", "Atención"],
  },
  {
    id: 4,
    title: "Fundamentos de Redes Neuronales",
    type: "video",
    concept: "Redes Neuronales",
    difficulty: "Básico",
    duration: "25 min",
    rating: 4.7,
    reason: "Tu dominio en Redes Neuronales es bajo (45%). Este video cubre los fundamentos esenciales.",
    content: "Video sobre fundamentos de redes neuronales...",
    confidence: 94,
    improvement: 15,
    isRecommended: true,
    tags: ["Perceptrón", "Activación", "Capas"],
  },
  {
    id: 5,
    title: "Python para Machine Learning",
    type: "reading",
    concept: "Python Básico",
    difficulty: "Básico",
    duration: "15 min",
    rating: 4.5,
    reason: "Complementa tu dominio actual en Python (75%) con técnicas específicas de ML.",
    content: "Lectura sobre Python para Machine Learning...",
    confidence: 78,
    improvement: 4,
    isRecommended: false,
    tags: ["NumPy", "Pandas", "Scikit-learn"],
  },
  {
    id: 6,
    title: "Introducción a Knowledge Tracing",
    type: "video",
    concept: "Knowledge Tracing",
    difficulty: "Básico",
    duration: "12 min",
    rating: 4.3,
    reason: "Base teórica del modelo SAKT que usa esta plataforma. Útil para entender tus métricas.",
    content: "Video introductorio sobre Knowledge Tracing...",
    confidence: 82,
    improvement: 3,
    isRecommended: false,
    tags: ["BKT", "IRT", "SAKT"],
  },
  {
    id: 7,
    title: "Quiz: Conceptos de Inteligencia Artificial",
    type: "exercise",
    concept: "Introducción a IA",
    difficulty: "Básico",
    duration: "20 min",
    rating: 4.4,
    reason: "Evalúa y refuerza tu comprensión general de IA.",
    content: "¿Cuál es la diferencia entre Machine Learning y Deep Learning?\n\nSelecciona la respuesta correcta:",
    confidence: 85,
    improvement: 7,
    isRecommended: false,
    tags: ["IA General", "Evaluación"],
  },
  {
    id: 8,
    title: "Convolutional Neural Networks - CNN",
    type: "video",
    concept: "Deep Learning",
    difficulty: "Avanzado",
    duration: "35 min",
    rating: 4.9,
    reason: "Siguiente paso tras dominar redes densas. Alta correlación con tu trayectoria de aprendizaje.",
    content: "Video sobre CNN...",
    confidence: 76,
    improvement: 10,
    isRecommended: false,
    tags: ["Visión", "Convolución", "Pooling"],
  },
];
